name: talon_win_query_regsystemconfigvalueupdate
description: Base query for registry events related to system configuration or security.
visualization:
  options:
    cell-overflow: wrap-text
    column-overflow: truncate
    configured-columns: {}
    row-numbers-enabled: false
  type: table-view
labels:
- talon_hunt_framework
- query
- asepvalueupdate
- windows
$schema: https://schemas.humio.com/query/v0.6.0
timeInterval:
  isLive: false
  start: 15m
queryString: |-
  // =====================================================
  // SEARCH
  // =====================================================
  #event_simpleName=RegSystemConfigValueUpdate event_platform=Win

  // =====================================================
  // SEARCH ASSETS
  // =====================================================
  | $talon_convert_time_utc()
  | $talon_utility_falcon_helper()
  | $talon_win_normalize_regsystemconfigvalueupdate()

  // =====================================================
  // TABLE
  // =====================================================
  | table(
      [
          utc_time,
          ComputerName,
          RegObjectName,
          RegStringValue,
          RegValueName,
          RegType,
          RegOperationType,
          RegClassification,
          RegClassificationFlags
      ],
      limit=max
  )
